- menu_name: "Servisler"

- name: "İletişim"
  url: "/"
  title: "İletişim"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap"
